[#48](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/48)
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #1
Opened 2020-09-13 00:17 UTC by Rafaelltm

### **Descrição do Problema**

Criar o CRUD de paciente, e desenvolver as telas de login e cadastro inicial da aplicação de acordo com o protótipo.

### **Topicos a serem abordados:**

- [x] tela de login
- [x] tela de cadastro
- [ ] endpoints para Criar, deletar, editar e visualizar as informações do usuário paciente
- [ ] criar UI para os endpoints

2020-09-13 03:28 UTC, joberthrogers18 commented on src/pages/LandingLogin/index.js
> +            }
Eu não sei se esse alert fica muito bom para o UX, inda mais quando for criar as telas responsivas. Uma opção seria usar algo parecido com esses: https://react-bootstrap.github.io/components/alerts/.

Mas não precisa ser agora, a gente pode deixar pra refatorar proxima sprint

2020-09-13 03:33 UTC, joberthrogers18 commented on src/pages/LandingSignUp01/styles.css
> +    */
Por favor, tira esse comentário daqui!

2020-09-13 03:38 UTC, joberthrogers18 commented on src/pages/LandingSignUp02/index.js
> +                phone: props.location.state.phone,
Para deixar essa parte mais verbosa você poderia criar uma variável intermediaria desestruturando de props.location.state, da seguinte forma:

```const { name, lastaName, email, phone} = location.state.name```

e aplicar depois no objeto. Acho que vai ficar mais padronizado!

2020-09-13 03:40 UTC, joberthrogers18 commented
@vinelime e @Rafaelltm, tenta depois rodar o lint fix ai no código, o code climate apontou alguns erros lint... E se possível tentar arrumar algo que ele apontou a mais.

2020-09-13 03:42 UTC, joberthrogers18 requested changes
Tentem fazer essa mudanças que apontei aqui no Front em relação ao código, irei testar todo o fluxo jája e ver se tudo está funcionando normalmente!

2020-09-15 21:28 UTC, DanMke commented
- o nome dos atributos está diferente no front-end e no back-end => exemplo: surname -> lastName, entre outros (Não está salvando no banco por causa disso)
- props.location.state.name => registration-step02
- Event prevent default nos forms das páginas
- Feedback do cadastro -> se tiver erro mostrar onde está o erro, e se cadastrar dar um aviso e redirecionar
- Desestruturar dados do body para manipular os dados de usuário paciente (inserir usuário)
- Coisas em portugues -> alerts e senha/setSenha
- Não possui endpoint de login -> endpoint que vai receber o email e a senha e verificar no banco se existe um usuario com esse email e senha
- Linkar frontend no endpoint de login

2020-09-16 01:03 UTC, merged