Design Correction
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #11
Opened 2020-10-02 02:12 UTC by Rafaelltm

## Descrição

Correção do design e do fluxo de páginas.

## _Issue_ Relacionada

[FIX - Correções de Design #74](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/74)

## Motivação e Contexto

A alteração é necessária para deixar o fluxo correto bem como deixar a aplicação mais agradável aos olhos do usuário

## Como isso foi testado?

Utilizando o insomnia e subindo a aplicação no docker

## Captura de tela (quando necessário):

## Tipo de mudanças

- [x] _Bug fix_ (modificação na qual conserta um _issue_ e não modifica recursos já existentes)
- [ ] Nova _feature_ (modificação na qual adiciona uma nova _feature_ e não modificar _features_ já existentes)
- [ ] Mudança disruptiva (_Breaking change_) (Correção ou _features_ que altera _features_ já existentes)

## Lista de controle:

- [x] Meu código segue o estilo de código deste projeto.
- [x] Meus _commits_ seguem o padrão de estilo deste projeto.
- [ ] Minha mudança requer uma mudança na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ ] Eu adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes novos e existentes foram aprovados.

2020-10-03 14:33 UTC, joberthrogers18 commented on src/components/NavBar.js
> +                    {/* <Link className="a" to="" >Próximos Eventos</Link> */}
Pessoal de EPS deixaram esse comentário, pq ainda não há essa funcionalidade!

2020-10-03 14:33 UTC, joberthrogers18 commented on src/components/NavBar.js
> +                    {/* <Link className="a" to="" >Próximos Eventos</Link> */}
Pessoal de EPS deixaram esse comentário, pq ainda não há essa funcionalidade!

2020-10-03 14:38 UTC, joberthrogers18 commented on src/pages/PsyProfile/index.js
> +                        {/* <Link className="link" to="/" >Alterar Senha</Link> */}
Pessoal de EPS deixaram esse comentário, pq ainda não há essa funcionalidade!

2020-10-03 15:42 UTC, joberthrogers18 commented
Pessoal. acho que a fonte ta muito grande, se pudesse diminuir e centralizar verticalmente; Pelo que eu vi só deram um margin top de 16% o que não é muito legal. Só centralizar que é sucesso!
![image](https://user-images.githubusercontent.com/19327076/94995488-fafa8780-0574-11eb-9f51-96dde0b488f2.png)

2020-10-03 16:01 UTC, joberthrogers18 commented
Pessoal, eu achei um bug. Quando eu me entrei como psicólogo  ele foi para a página de perfil de psicólogo normal, ai eu fui em patient list e logo após eu cliquei em no link de perfil e ele apareceu o forms de alteração de perfil de usuário, como mostrado abaixo.
![testeee](https://user-images.githubusercontent.com/19327076/94996037-8aee0080-0578-11eb-9538-eb3ae2ffa794.gif)

2020-10-03 16:03 UTC, joberthrogers18 requested changes
Achei só esses errinhos de design, mas ta muito bom galera o/ Só arrumar que eu aprovo!

2020-10-04 00:57 UTC, jplpereira commented
Fui testar aqui e deu problema na hora de realizar o cadastro. Apresentou um erro na hora de fazer, mas a mensagem não fala qual foi o erro.

![image](https://user-images.githubusercontent.com/13935419/95004588-77b45280-05c3-11eb-8210-eb5516ce5779.png)

2020-10-04 01:28 UTC, jplpereira commented
Na página do prontuário, a navbar só aparece quando o navegador é colocado em tela cheia

![image](https://user-images.githubusercontent.com/13935419/95004857-2e660200-05c7-11eb-8426-d68c1fdf0f1a.png)

2020-10-04 05:00 UTC, joberthrogers18 commented
Outra coisa é que agora ta ficando centralizado a lista, acho que é melhor deixar só o aviso que não já nada
![image](https://user-images.githubusercontent.com/19327076/95007378-fec1f480-05dc-11eb-90dc-f7223600ed69.png)

2020-10-04 05:02 UTC, joberthrogers18 commented
Quando eu vou para psylist e depois volto para a tela de psicologo ele não carrega as informações. Ficando assim:
![image](https://user-images.githubusercontent.com/19327076/95007392-48aada80-05dd-11eb-9138-2be39340c949.png)

2020-10-04 05:06 UTC, joberthrogers18 commented
Quando não há pacientes na tela de pyschology list, não há nenhum aviso de que não há pacientes cadastrados. O usuário pode ficar confuso se está ainda carregando ou se travou...
![image](https://user-images.githubusercontent.com/19327076/95007417-c66ee600-05dd-11eb-9f9c-09dcb32d9974.png)

2020-10-04 17:28 UTC, Rafaelltm commented
> Quando eu vou para psylist e depois volto para a tela de psicologo ele não carrega as informações. Ficando assim:
> ![image](https://user-images.githubusercontent.com/19327076/95007392-48aada80-05dd-11eb-9138-2be39340c949.png)

@joberthrogers18 , não estou conseguindo reproduzir esse erro aqui. Poderia me explicar melhor o que você fez para chegar a ele?

2020-10-04 17:39 UTC, joberthrogers18 commented
> > Quando eu vou para psylist e depois volto para a tela de psicologo ele não carrega as informações. Ficando assim:
> > ![image](https://user-images.githubusercontent.com/19327076/95007392-48aada80-05dd-11eb-9138-2be39340c949.png)
> 
> @joberthrogers18 , não estou conseguindo reproduzir esse erro aqui. Poderia me explicar melhor o que você fez para chegar a ele?

@Rafaelltm Não teria que retornar os dados já existentes do usuário no forms? Ele não está retornando, era disso que eu estava falando...

2020-10-04 17:41 UTC, Rafaelltm commented
> > > Quando eu vou para psylist e depois volto para a tela de psicologo ele não carrega as informações. Ficando assim:
> > > ![image](https://user-images.githubusercontent.com/19327076/95007392-48aada80-05dd-11eb-9138-2be39340c949.png)
> > 
> > 
> > @joberthrogers18 , não estou conseguindo reproduzir esse erro aqui. Poderia me explicar melhor o que você fez para chegar a ele?
> 
> @Rafaelltm Não teria que retornar os dados já existentes do usuário no forms? Ele não está retornando, era disso que eu estava falando...

Então, é que para mim eu estou navegando pra testar e os dados estão sendo retornados no forms

2020-10-04 17:43 UTC, joberthrogers18 commented
@Rafaelltm, então eu devo ter me engando... Só não posso testar agora, mas se vc esta falando que não ta dando o erro eu acredito. Só arrumar o resto então e a gente aprova. Tmj!

2020-10-04 17:44 UTC, Rafaelltm commented
> @Rafaelltm, então eu devo ter me engando... Só não posso testar agora, mas se vc esta falando que não ta dando o erro eu acredito. Só arrumar o resto então e a gente aprova. Tmj!

Beleza, valeu

2020-10-05 12:32 UTC, joberthrogers18 approved these changes

2020-10-06 00:16 UTC, merged