Fix/front repairs
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #19
Opened 2020-11-07 01:38 UTC by PerhapsAlex

Melhorar o design da plataforma para melhorar a sua usabilidade.

## Descrição

## _Issue_ Relacionada
https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/101

## Motivação e Contexto

Implementar as mudanças feitas no protótipo de alta fidelidade

## Captura de tela (quando necessário):
![Captura_de_tela_de_2020-11-06_22-31-49](https://user-images.githubusercontent.com/40877204/98428464-5641fd00-2080-11eb-9948-55261ea17d04.png)
![Captura_de_tela_de_2020-11-06_22-31-37](https://user-images.githubusercontent.com/40877204/98428466-56da9380-2080-11eb-972e-329066fc1ba9.png)
![Captura_de_tela_de_2020-11-06_22-31-22](https://user-images.githubusercontent.com/40877204/98428467-57732a00-2080-11eb-956a-0878b9223eac.png)
![Captura_de_tela_de_2020-11-06_22-31-00](https://user-images.githubusercontent.com/40877204/98428468-580bc080-2080-11eb-9a97-1e83b5ecbfee.png)
![Screenshot from 2020-11-06 22-30-59](https://user-images.githubusercontent.com/40877204/98428469-580bc080-2080-11eb-9caa-ccdbb4c04a2d.png)
![Screenshot from 2020-11-06 22-30-48](https://user-images.githubusercontent.com/40877204/98428470-58a45700-2080-11eb-874f-703d02552ca7.png)

## Tipo de mudanças

- [x] _Bug fix_ (modificação na qual conserta um _issue_ e não modifica recursos já existentes)
- [x] Nova _feature_ (modificação na qual adiciona uma nova _feature_ e não modificar _features_ já existentes)
- [x] Mudança disruptiva (_Breaking change_) (Correção ou _features_ que altera _features_ já existentes)

## Lista de controle:

- [x] Meu código segue o estilo de código deste projeto.
- [x] Meus _commits_ seguem o padrão de estilo deste projeto.
- [ ] Minha mudança requer uma mudança na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ ] Eu adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes novos e existentes foram aprovados.

2020-11-10 00:06 UTC, DanMke commented
<img width="569" alt="Screen Shot 2020-11-09 at 21 02 37" src="https://user-images.githubusercontent.com/31926918/98610680-e70e1800-22ce-11eb-83b1-f2ae6bebd743.png">

Na tela de login aumentar um pouco o tamanho da fonte do "Esqueci a minha senha" e "Ainda não possuo uma conta" e colocar sublinhado

2020-11-10 00:11 UTC, DanMke commented
<img width="1792" alt="Screen Shot 2020-11-09 at 21 11 10" src="https://user-images.githubusercontent.com/31926918/98611146-1a04db80-22d0-11eb-8c02-e682c3b60c98.png">

Façam o merge com a develop para ver se os erros de autenticação somem!

Deem uma olhada nesse outro erro "Error while trying to use the following icon from the Manifest: http://localhost:3000/logo192.png (Download error or resource isn't a valid image)"

2020-11-10 00:13 UTC, DanMke commented
Os alerts estão sumindo muito rápido, não está dando tempo de ler, é preciso aumentar o tempo de visualização dos alerts

2020-11-10 00:17 UTC, DanMke commented
<img width="1782" alt="Screen Shot 2020-11-09 at 21 16 52" src="https://user-images.githubusercontent.com/31926918/98611559-e5455400-22d0-11eb-8e2d-8622e645eb54.png">

Na página de login de admin, não tem o card no fundo que nem no login normal
e também, os componentes da tela estão muito juntos, e a foto não é necessária!

2020-11-10 00:19 UTC, DanMke commented
<img width="1341" alt="Screen Shot 2020-11-09 at 21 18 40" src="https://user-images.githubusercontent.com/31926918/98611677-25a4d200-22d1-11eb-9945-1a584cb7f3a7.png">

Nesta tela de cadastro de psicólogos também está sem o card e com a imagem desnecessária!

2020-11-10 00:23 UTC, DanMke commented
<img width="1584" alt="Screen Shot 2020-11-09 at 21 22 41" src="https://user-images.githubusercontent.com/31926918/98611912-b54a8080-22d1-11eb-8340-aa460a8ae60c.png">

O card está muito perto da navbar, seria bom se fosse mais centralizado na tela!

Os campos dentro do card estão próximos dos cantos, seria bom deixar um pouco mais de espaço entre os cantos.

2020-11-10 00:25 UTC, DanMke commented
<img width="1168" alt="Screen Shot 2020-11-09 at 21 25 09" src="https://user-images.githubusercontent.com/31926918/98612047-0ce8ec00-22d2-11eb-8022-7350a0e8cc16.png">
Deixar a foto e o nome mais centralizado e dar um destaque ao nome do usuário

2020-11-10 00:31 UTC, DanMke commented
<img width="1667" alt="Screen Shot 2020-11-09 at 21 28 27" src="https://user-images.githubusercontent.com/31926918/98612245-82ed5300-22d2-11eb-8b14-f923d50cc1f4.png">

* Deixar o lado direito menor
* Dar espaço do título "Suas Restrições:" de cima e do lado esquerdo
* Deixar os botões como ficam quando passa o mouse em cima, e no hover escurecer um pouco

2020-11-10 00:31 UTC, DanMke requested changes
@PerhapsAlex @pedroholiveira1998

2020-11-11 00:10 UTC, pedroholiveira1998 commented
@DanMke @joberthrogers18 @jplpereira Podem conferir as mudanças por favor?

2020-11-12 23:13 UTC, joberthrogers18 commented
Por mim parece de boas, só faz o rebase e tenta arrumar esses warnings que é sucesso

2020-11-12 23:13 UTC, joberthrogers18 approved these changes

2020-11-12 23:42 UTC, merged