WiP-waiting list
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #20
Opened 2020-11-09 23:31 UTC by Rafaelltm

## Descrição

Criação da tela para acompanhamento da posição na lista de espera de determinado psicólogo

## _Issue_ Relacionada

![US14 - Implementação da lista de espera #98](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/98)

## Motivação e Contexto

Esta alteração é necessária pois as clientes solicitaram que houvesse um meio de o paciente entrar na lista de espera caso não houvessem mais vagas para um determinado psicólogo.

## Como isso foi testado?

Utilizando o insomnia para a criação de usuarios e navegando pela própria aplicação

## Captura de tela (quando necessário):

## Tipo de mudanças

- [ ] _Bug fix_ (modificação na qual conserta um _issue_ e não modifica recursos já existentes)
- [x] Nova _feature_ (modificação na qual adiciona uma nova _feature_ e não modificar _features_ já existentes)
- [ ] Mudança disruptiva (_Breaking change_) (Correção ou _features_ que altera _features_ já existentes)

## Lista de controle:

- [x] Meu código segue o estilo de código deste projeto.
- [x] Meus _commits_ seguem o padrão de estilo deste projeto.
- [ ] Minha mudança requer uma mudança na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ ] Eu adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes novos e existentes foram aprovados.

2020-11-12 23:40 UTC, joberthrogers18 commented
Galera, achei o design muito simples.
![image](https://user-images.githubusercontent.com/19327076/99009620-b02e4100-251e-11eb-819a-bd6fbdce769f.png)
Tenta padronizar os campos com o que nós tempos, talvez seria melhor colocar esse confiram como azul, já que todos os botões da plataforma pra confirmação estão nessa cor, além do mais o campos estão muito juntos tenta da uma margem entre cada um

2020-11-12 23:42 UTC, joberthrogers18 commented
O erro ta muito simples também, nada muito chamativo. Tenta colocar mudar a cor pra vermelho ou algo do tipo
![image](https://user-images.githubusercontent.com/19327076/99009871-2af75c00-251f-11eb-81aa-389a2a5a6b5c.png)

2020-11-12 23:47 UTC, joberthrogers18 requested changes
Acho que só melhorar o design que é sucesso

2020-11-12 23:59 UTC, joberthrogers18 commented
Galera desconsidera aqui por enquanto eu tava comentando no PR errado

2020-11-13 00:17 UTC, joberthrogers18 commented
Quando tento cadastrar um agendamento ele me retorna um erro que fica no card em cima e isso no console
![image](https://user-images.githubusercontent.com/19327076/99012121-0782e000-2524-11eb-854c-5fff021ec368.png)

2020-11-13 00:23 UTC, joberthrogers18 commented
Quando deixo em branco em a duração ele fica parado carregando infinitamente

2020-11-13 00:23 UTC, joberthrogers18 requested changes
Pessoal, vejam esses erros por favor, isso é de extrema urgencia

2020-11-17 02:30 UTC, DanMke requested changes
Arrumar erros do codeclimate

2020-11-20 22:37 UTC, joberthrogers18 approved these changes
Aprovado!

2020-11-23 22:28 UTC, merged