Update password
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #21
Opened 2020-11-12 19:26 UTC by Rafaelltm

## Descrição

Adicionando a função de atualizar a senha do usuário.

## _Issue_ Relacionada

![US16 - Implementar a modificação de senha dos usuários #107](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/107)

## Motivação e Contexto

Os usuários da plataforma devem ter a opção de modificar a senha de acesso conforme sua necessidade.

## Como isso foi testado?

Foi testado navegando pela própria aplicação, e utilizando o insomnia

## Captura de tela (quando necessário):

## Tipo de mudanças

- [ ] _Bug fix_ (modificação na qual conserta um _issue_ e não modifica recursos já existentes)
- [x] Nova _feature_ (modificação na qual adiciona uma nova _feature_ e não modificar _features_ já existentes)
- [ ] Mudança disruptiva (_Breaking change_) (Correção ou _features_ que altera _features_ já existentes)

## Lista de controle:

- [x] Meu código segue o estilo de código deste projeto.
- [x] Meus _commits_ seguem o padrão de estilo deste projeto.
- [ ] Minha mudança requer uma mudança na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ ] Eu adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes novos e existentes foram aprovados.

2020-11-12 23:58 UTC, joberthrogers18 commented
Galera, achei o design muito simples.
![image](https://user-images.githubusercontent.com/19327076/99009620-b02e4100-251e-11eb-819a-bd6fbdce769f.png)
Tenta padronizar os campos com o que nós tempos, talvez seria melhor colocar esse confiram como azul, já que todos os botões da plataforma pra confirmação estão nessa cor, além do mais o campos estão muito juntos tenta da uma margem entre cada um

2020-11-12 23:58 UTC, joberthrogers18 commented
O erro ta muito simples também, nada muito chamativo. Tenta colocar mudar a cor pra vermelho ou algo do tipo
![image](https://user-images.githubusercontent.com/19327076/99009871-2af75c00-251f-11eb-81aa-389a2a5a6b5c.png)

2020-11-12 23:58 UTC, joberthrogers18 commented
Por favor, corrija os conflitos

2020-11-13 00:01 UTC, joberthrogers18 requested changes
Por favor corrija esses pontos levantados pra gente manter o app padronizado

2020-11-17 04:37 UTC, Rafaelltm commented
Como tinhamos conversado na daily de quarta passada, eu arrumei o que consegui. Mas não estou conseguindo estilizar o modal por algum motivo. Só deixando registrado para quando forem reavaliar o pr

2020-11-18 00:20 UTC, joberthrogers18 commented
@Rafaelltm agora ta assima qui, 
![image](https://user-images.githubusercontent.com/19327076/99466153-4513ae80-2912-11eb-931e-6bfe116ebbff.png)
se ficar ruim de arrumar isso ai, volta pra como tava antes e ai a gente mergea. Depois a gente pode ver como estilizar isso melhor

2020-11-18 00:25 UTC, joberthrogers18 requested changes
Tentem ver essa extrapolação pra fora do modal, e qualquer  coisa se tiver muito difícil de estilizar voltem pra o padrão que tava antes, e em outra sprint a gente foca em mudar isso pra algo melhor!

2020-11-20 18:54 UTC, joberthrogers18 approved these changes
Pessoal to vendo que ta quebrado o design ainda, como já ta feito e funcional eu vou aprovar e depois a gente refatora isso...

2020-11-20 19:18 UTC, merged