User Infos
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #27
Opened 2020-11-20 22:20 UTC by Rafaelltm

## Descrição

Atualizamos os campos necessários para o usuário preencher no perfil, para que os profissionais tenham mais informações sobre os pacientes.

## _Issue_ Relacionada

![FIX: Refatoração do cadastro do usuário paciente #111](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/111)

## Motivação e Contexto

O perfil de usuário tinha poucos campos a serem preenchidos, gerando a necessidade de pegar mais informações sobre os pacientes.

## Como isso foi testado?

Foi testado utilizando o próprio app, e o insomnia para cadastrar usuários para teste.

## Captura de tela (quando necessário):

## Tipo de mudanças

- [x] _Bug fix_ (modificação na qual conserta um _issue_ e não modifica recursos já existentes)
- [ ] Nova _feature_ (modificação na qual adiciona uma nova _feature_ e não modificar _features_ já existentes)
- [ ] Mudança disruptiva (_Breaking change_) (Correção ou _features_ que altera _features_ já existentes)

## Lista de controle:

- [x] Meu código segue o estilo de código deste projeto.
- [x] Meus _commits_ seguem o padrão de estilo deste projeto.
- [ ] Minha mudança requer uma mudança na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ ] Eu adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes novos e existentes foram aprovados.

2020-11-22 03:43 UTC, joberthrogers18 commented
Pessoal. na hora de preencher eu fui ficando confuso sobre a qual campo aquela informação pertencia. Quando há o placeholder é tranquilo saber, mas vamo supor que usuário queira verificar se tudo está conforme ele espera e se não tem nenhum erro, ele vai ficar perdido sobre as informações que ele preencheu.

Acho que seria bom colocar uma label acima de cada campo, sei que essa tela vai mudar, mas acho que esse campo ai vai ficar mais verboso se colocar a label para cada campo... Creio que é algo rápido de implementar e vai ser de boas, por isso to pedindo pra essa sprint! Valeuuu

![image](https://user-images.githubusercontent.com/19327076/99893106-91345b00-2c52-11eb-8615-f7ca499545e7.png)

2020-11-22 03:44 UTC, joberthrogers18 requested changes
Pessoal, de resto ta massa, só peço que faça essa modificação que levantei se puder, ai aprovo o PR!

2020-11-22 15:00 UTC, jplpereira commented
Quando a tela é colocada no celular, como o telefone dos pais é o último campo do lado esquerdo e o do usuário é o primeiro do lado direito, eles acabam ficando um em cima do outro e pode acabar confundindo o usuário. O ideal é identificar de uma forma mais clara os campos nos _placeholders_ e padronizar colocando a necessidade do DDD no telefone dos pais também.

![image](https://user-images.githubusercontent.com/13935419/99907098-9e386500-2cb9-11eb-88d5-4a3b1f5aa8e2.png)

2020-11-22 15:02 UTC, jplpereira commented
No campo do estado civil falou a opção "união estável"

![image](https://user-images.githubusercontent.com/13935419/99907246-7f869e00-2cba-11eb-8749-a902dffa110b.png)

2020-11-22 15:03 UTC, jplpereira commented
No campo de gênero tem que ajustar as opções para mulher, homem, mulher trans, homem trans, não-binário, prefiro não dizer

![image](https://user-images.githubusercontent.com/13935419/99907268-a7760180-2cba-11eb-8fea-36eb7e05a7d4.png)

2020-11-22 15:05 UTC, jplpereira commented
No campo etnia faltou a opção "amarela(o)"

![image](https://user-images.githubusercontent.com/13935419/99907329-fd4aa980-2cba-11eb-8a47-deb596a9249e.png)

2020-11-22 15:06 UTC, jplpereira commented
No campo de vínculo, as opções devem ser "docente, estudante de graduação, estudante de mestrado, estudante de doutorado, técnico-administrativo, não tenho vínculo com a UnB;"

![image](https://user-images.githubusercontent.com/13935419/99907355-24a17680-2cbb-11eb-9e05-25677d4a693a.png)

2020-11-22 15:14 UTC, jplpereira commented
Quando a tela é colocada no celular, o campo da medicação corta uma parte do placeholder. Como o @joberthrogers18 pediu pra colocar as labels acima dos campos, acredito que seja melhor colocar essa pergunta na label com uma quebra de linha

![image](https://user-images.githubusercontent.com/13935419/99907567-3b949880-2cbc-11eb-9b8c-6ebd70403092.png)

2020-11-22 15:23 UTC, pedroholiveira1998 commented
Concordo, faremos as modificações.

2020-11-23 06:22 UTC, Rafaelltm commented
Pessoal, arummei a questão dos labels e o css para a tela quando estiver no celular. Mas da forma que pensei, quando voltei para o tamanho normal de tela o final do "form" não está completamente alinhado. Gostaria que vocês dessem uma olhada para ver se acham "ok" a forma como está ou se tem alguma outra sugestão

2020-11-23 06:23 UTC, Rafaelltm commented
E sobre essas 3 issues do code climate na minha opinião deveriam ser desativadas.

2020-11-27 23:37 UTC, joberthrogers18 approved these changes

2020-11-28 22:18 UTC, merged