Feature/admin user
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #3
Opened 2020-09-20 22:09 UTC by luisgfmarques

## Descrição
## _Issue_ Relacionada
[#55 Implementação do Usuário Administrador](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/55)

## Motivação e Contexto

Criação de Usuario admin, adição de Psicólogos ao sistema 
## Como isso foi testado?

## Captura de tela (quando necessário):

## Tipo de mudanças

- [ ] _Bug fix_ (modificação na qual conserta um _issue_ e não modifica recursos já existentes)
- [ x] Nova _feature_ (modificação na qual adiciona uma nova _feature_ e não modificar _features_ já existentes)
- [ ] Mudança disruptiva (_Breaking change_) (Correção ou _features_ que altera _features_ já existentes)

## Lista de controle:

- [ x] Meu código segue o estilo de código deste projeto.
- [x ] Meus _commits_ seguem o padrão de estilo deste projeto.
- [ ] Minha mudança requer uma mudança na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [ x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ x] Eu adicionei testes para cobrir minhas alterações.
- [ x] Todos os testes novos e existentes foram aprovados.

2020-09-20 23:09 UTC, joberthrogers18 commented
Te, vários erros no lint e tem conflito para ser corrigido!

2020-09-20 23:14 UTC, joberthrogers18 commented on src/pages/AdminMain/index.js
> +}
Vocês usaram componente com classe aqui e nos outros funcionais. Mantém todos padronizado com os hooks e funções. Que é a nova versão do React

2020-09-20 23:16 UTC, joberthrogers18 requested changes
Por favor aplique as mudanças pedidas!

2020-09-21 12:31 UTC, DanMke commented
Faltou preencher melhor a descrição do Pull Request, acertar os checkboxes e preencher os tópicos corretamente.

2020-09-21 12:36 UTC, DanMke commented
Preencher também a barra lateral direita do GitHub -> Reviewers, Assignees..

2020-09-21 12:50 UTC, DanMke commented
Ainda possuem algumas issues do codeclimate possíveis de arrumar.
As issues de Similar blocks of code, Cognitive Complexity e lines of code podem deixar, foquem nas outras para entregar.

2020-09-21 14:13 UTC, DanMke commented
Pessoal, o design também não está legal, porém as funcionalidades estão cumpridas, irá ter uma issue para arrumar esse design

2020-09-21 19:01 UTC, joberthrogers18 approved these changes

2020-09-21 20:39 UTC, merged