WIP-Feature/forget password
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #31
Opened 2020-12-01 00:05 UTC by luisgfmarques

## Descrição
Foi adicionado a funcionalidade de Esqueci minha senha, que envia um email para o paciente/psicologo com a nova senha gerada automaticamente, é no primeiro login com a senha gerada, o usuario e automaticamente redirecionado para a pagina de atualização de senha.

## _Issue_ Relacionada
[US17 - Implementar a recuperação da senha #121](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/121)

## Motivação e Contexto
Eu , como psicologo/usuario , gostaria de recuperar o acesso na plataforma, caso eu esqueça a minha senha

## Como isso foi testado?

## Captura de tela (quando necessário):
![Captura de tela de 2020-11-30 20-53-39](https://user-images.githubusercontent.com/49294754/100680052-857e1e00-334f-11eb-8c0e-227cb248d6cd.png)
![Captura de tela de 2020-11-30 20-54-56](https://user-images.githubusercontent.com/49294754/100680058-89aa3b80-334f-11eb-9ddb-a0fec8cbe504.png)

## Tipo de mudanças

- [ ] _Bug fix_ (modificação na qual conserta um _issue_ e não modifica recursos já existentes)
- [x] Nova _feature_ (modificação na qual adiciona uma nova _feature_ e não modificar _features_ já existentes)
- [ ] Mudança disruptiva (_Breaking change_) (Correção ou _features_ que altera _features_ já existentes)

## Lista de controle:

- [x] Meu código segue o estilo de código deste projeto.
- [x] Meus _commits_ seguem o padrão de estilo deste projeto.
- [ ] Minha mudança requer uma mudança na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ ] Eu adicionei testes para cobrir minhas alterações.
- [x] Todos os testes novos e existentes foram aprovados.

2020-12-01 23:48 UTC, joberthrogers18 commented
Galera,  o Daniel conseguimos estilizar esse modal, se puder pegar o css de la aplicar ai provavelmente vai ficar no padrão

2020-12-01 23:50 UTC, joberthrogers18 requested changes
Verifiquem o esquema da estilização que está na branch que ta sendo feita refatoração e aplica ai, esse modal ele ta bem estranho. Depois que fizer isso, eu aprovo!

2020-12-02 03:06 UTC, DanMke requested changes
A branch que o jobs disse acima: https://github.com/fga-eps-mds/2020.1-eSaudeUnB-FrontEnd/tree/fix/esaude_improvements
Utilizem o padrão da modal de Alterar Senha do profile do user!

2020-12-03 20:14 UTC, luisgfmarques commented
Apontem as mudanças necessárias ainda 

![Captura de tela de 2020-12-03 17-12-07](https://user-images.githubusercontent.com/49294754/101082839-e2b1e380-358a-11eb-99c1-5ad4f0837f15.png)

2020-12-05 00:21 UTC, joberthrogers18 approved these changes
Aprovado!

2020-12-05 00:32 UTC, DanMke approved these changes

2020-12-05 00:41 UTC, merged