Fix/improvement pages
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #34
Opened 2020-12-04 23:02 UTC by PerhapsAlex

## Descrição

O fluxo da pagina de cadastro das informações do usuário paciente foi modificado, agora ha um comportamento de abas na paginas no registro. 

Agora ao cadastrar um novo atendimento o profissional deve preencher a data e o horário que a consulta foi realizada. As datas agora também aparecem nas abas da pagina do prontuario. A sessão de preencher o nome do profissional foi descontinuada do prontuario, agora esta sendo obtido a partir das informações da sessão do usuário logado na plataforma

## _Issue_ Relacionada
[FIX - Mudança evolutiva do cadastro do usuário paciente #123](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/123)
[FIX - Mudança evolutiva do prontuário #117](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/117)

## Motivação e Contexto

Por conta da grande quantidade de campos que os usuários paciente devem preencher para que o seu acolhimento seja feito pelas profissionais, a tela de cadastro está com uma extensão grande na vertical fazendo o paciente tenha que rolar muito a tela para baixo. Além disso, após reunião com as clientes, algumas sugestões foram dadas pelas clientes, conforme tabela em anexo.

O prontuário dos pacientes deve evoluir para facilitar o trabalho de cadastramento dos atendimentos realizados pelos profissionais envolvidos no projeto.

## Como isso foi testado?

## Captura de tela (quando necessário):

## Tipo de mudanças

- [ ] _Bug fix_ (modificação na qual conserta um _issue_ e não modifica recursos já existentes)
- [x] Nova _feature_ (modificação na qual adiciona uma nova _feature_ e não modificar _features_ já existentes)
- [ ] Mudança disruptiva (_Breaking change_) (Correção ou _features_ que altera _features_ já existentes)

## Lista de controle:

- [x] Meu código segue o estilo de código deste projeto.
- [x] Meus _commits_ seguem o padrão de estilo deste projeto.
- [ ] Minha mudança requer uma mudança na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ ] Eu adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes novos e existentes foram aprovados.

2020-12-07 14:39 UTC, joberthrogers18 commented
@PerhapsAlex e @luisgfmarques eu curti pra caramba esse novo design do editar usuário. Ficou show demais. Mas vi que a cada vez que clica na seta ele faz uma nova requisição para o serve e acho que isso não é muito bom para a experiência do usuário. Creio que seja melhor salvar apenas quando ele clicar em "salvar".

![image](https://user-images.githubusercontent.com/19327076/101364031-7c71dd00-3878-11eb-9bda-9c9c42463b3a.png)

2020-12-07 14:43 UTC, joberthrogers18 commented
Galera acho que aqui podia ser o nome e sobrenome do paciente!
![image](https://user-images.githubusercontent.com/19327076/101364440-f3a77100-3878-11eb-8d4d-b7752f43cf84.png)

2020-12-07 14:46 UTC, joberthrogers18 commented
Quando eu não coloco a data e hora e preencho o resto ele retorna isso aqui:

![image](https://user-images.githubusercontent.com/19327076/101364900-78928a80-3879-11eb-8d59-71dc6c7b2a50.png)

2020-12-07 15:14 UTC, joberthrogers18 requested changes
Peço que realizem essas mudanças acima. Pois estão quebrando o fluxo e também interferindo no UX

2020-12-08 01:16 UTC, luisgfmarques commented
> Galera acho que aqui podia ser o nome e sobrenome do paciente. Além de já vim setado o horário e data atual como default para o usuário não se esquecer de colocar.
> ![image](https://user-images.githubusercontent.com/19327076/101364440-f3a77100-3878-11eb-8d4d-b7752f43cf84.png)


nome do Psicologo no caso ? sendo o nome e sobrenome ?

2020-12-09 22:29 UTC, joberthrogers18 commented
> > Galera acho que aqui podia ser o nome e sobrenome do paciente. Além de já vim setado o horário e data atual como default para o usuário não se esquecer de colocar.
> > ![image](https://user-images.githubusercontent.com/19327076/101364440-f3a77100-3878-11eb-8d4d-b7752f43cf84.png)
> 
> nome do Psicologo no caso ? sendo o nome e sobrenome ?

Isso ai mesmo Luís kkkkkk

2020-12-10 14:17 UTC, joberthrogers18 approved these changes

2020-12-10 14:18 UTC, merged