Feature/psychology calendar
fga-eps-mds/2020.1-eSaudeUnB-FrontEnd pull request #7
Opened 2020-09-26 23:19 UTC by PerhapsAlex

## Descrição
Foi adicionado a funcionalidade de marcação de disponibilidade pelos Psicólogos, sendo possível cadastrar horários de atendimento semanais para marcação de consulta e restringir consultas em dias específicos.
Para isso foi implementado uma lista dinâmica editavel e um calendário interativo.

## _Issue_ Relacionada
[US07 - Cadastrar a disponibilidade dos profissionais de psicologia #65](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki/issues/65)

## Motivação e Contexto

## Como isso foi testado?

## Captura de tela (quando necessário):

## Tipo de mudanças

- [ ] _Bug fix_ (modificação na qual conserta um _issue_ e não modifica recursos já existentes)
- [x] Nova _feature_ (modificação na qual adiciona uma nova _feature_ e não modificar _features_ já existentes)
- [ ] Mudança disruptiva (_Breaking change_) (Correção ou _features_ que altera _features_ já existentes)

## Lista de controle:

- [x] Meu código segue o estilo de código deste projeto.
- [x] Meus _commits_ seguem o padrão de estilo deste projeto.
- [ ] Minha mudança requer uma mudança na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [x] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ ] Eu adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes novos e existentes foram aprovados.

2020-09-27 13:31 UTC, joberthrogers18 commented
Tem conflito, por favor corrigir!

2020-09-27 13:42 UTC, joberthrogers18 commented on src/pages/PsychologistCalendar/index.js
> +                            </div> */}
Esse comentário é realmente necessário, ou será usado posteriormente? Se não for, por favor retirar!

2020-09-27 13:43 UTC, joberthrogers18 commented on src/pages/PsychologistSchedule/index.js
> +        console.log(Days);
Você deixou um console aqui, se não for necessário, por favor, retirar!!!

2020-09-27 13:46 UTC, joberthrogers18 commented
Tem conflitos com a develop, por favor corrigir. Se tiver alguma dúvida de como fazer, só mandar lá no canal de dúvidas do Slack!

2020-09-27 14:18 UTC, joberthrogers18 commented
@PerhapsAlex e @luisgfmarques, quando eu cadastro os horários disponiveis não tem nenhum feedback na tela, tenta colocar alguma div ou card pra sinalizar pro usuário se deu certo ou errado! E outra, ele ta deixando eu cadastrar mesmo quando há horário vazio.

![image](https://user-images.githubusercontent.com/19327076/94367160-d309b080-00aa-11eb-863e-5fd0f999d268.png)

2020-09-27 14:22 UTC, joberthrogers18 commented
Mesma coisa para a parte de restrições. Não tem feedback nenhum quando realiza ação!!

![image](https://user-images.githubusercontent.com/19327076/94367195-106e3e00-00ab-11eb-91c2-71046cb3f740.png)

Outra coisa é que quando eu coloco pra adicionar a restrição para um mesmo dia várias vezes, ele cadastrar mesmo assim! (Backend)!

![image](https://user-images.githubusercontent.com/19327076/94367216-46abbd80-00ab-11eb-8cdc-b2211faaa78e.png)

2020-09-27 14:25 UTC, joberthrogers18 requested changes
Encontrei esses erros, por favor fazer a correção!

2020-09-27 19:45 UTC, DanMke commented
Corrigir também os erros acusados pelo codeclimate!

2020-09-30 03:15 UTC, DanMke approved these changes

2020-09-30 03:19 UTC, DanMke commented
@PerhapsAlex @luisgfmarques só arrumar os conflitos e podem mergear!

2020-09-30 09:29 UTC, merged